sudo: false
language: node_js
node_js:
  - "stable"
  - "4.2"
  - "0.12"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libcairo2-dev
      - libjpeg8-dev
      - libpango1.0-dev
      - libgif-dev
      - g++-4.8
env:
  - CXX=g++-4.8
