language: node_js
node_js:
  - "4.2"
  - "0.12"
  - "0.10"
  - "0.8"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_install:
  - if [[ $TRAVIS_NODE_VERSION == 0.8 ]]; then npm install -g npm@1.4.28; fi
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then export CXX=g++-4.8; fi
  - $CXX --version
  - sudo chown -R $USER /usr/local
  - sh install
  - npm explore npm -g -- npm install node-gyp@latest
